version: 2.1
orbs:
  node: circleci/node@4.2.1
  github: topmonks/github@1.0.2
  slack: circleci/slack@4.4.0
jobs:
  build:
    executor:
      name: node/default
      tag: '14.16.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --immutable
          cache-version: v2
          cache-path: .yarn/cache
      - run:
          name: Build testing site
          command: yarn build
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
  merge_pr:
    docker:
      - image: cimg/base:2020.12
    steps:
      - checkout
      - github/install
      - github/merge_pr:
          rebase: true
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
workflows:
  ci:
    jobs:
      - build:
          context: org-global
      - node/test:
          context: org-global
          version: '14.16.0'
          pkg-manager: yarn
          override-ci-command: yarn install --immutable
          cache-version: v2
      - merge_pr:
          context: org-github
          requires:
            - build
            - node/test
          filters:
            branches:
              only: /dependabot\/.*/
