version: 2.1
orbs:
  node: circleci/node@5.0.0
  github: topmonks/github@1.0.2
  slack: circleci/slack@4.4.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: arm.medium
    steps:
      - checkout
      - run: nvm install $(< .nvmrc)
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v2
      - run:
          name: Build testing site
          command: yarn build
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
  test:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: arm.medium
    steps:
      - checkout
      - run: nvm install $(< .nvmrc)
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v2
      - run: yarn test
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
  merge_pr:
    docker:
      - image: cimg/base:2022.1
    steps:
      - checkout
      - github/install
      - github/merge_pr:
          rebase: true
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
workflows:
  ci:
    jobs:
      - build:
          context: org-global
      - test:
          context: org-global
      - merge_pr:
          context: org-github
          requires:
            - build
            - test
          filters:
            branches:
              only: /dependabot\/.*/
