version: 2.1
orbs:
  node: circleci/node@7.2.1
  slack: circleci/slack@6.1.3

jobs:
  build:
    executor:
      name: node/default
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Build testing site
          command: yarn build
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
  test:
    executor:
      name: node/default
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn-berry
      - run: yarn test
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-topmonks-webs
workflows:
  ci:
    jobs:
      - build:
          context: org-global
      - test:
          context: org-global
