version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:14.0
jobs:
  build:
    executor: node
    steps:
      - run: yarn install
      - run: yarn test
      - run: yarn build
workflows:
  ci:
    jobs:
      - build
